config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :project do 
    resources :group
    resources :attachments
    resources :topic do
      resources :messages
    end
  end
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :topic
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :groups
    has_many :user, through: :groups
    has_many :topic
    has_many_attached :files
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :project
    has_many :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :groups, dependent: :destroy
  has_many :projects, through: :groups

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
    
    def create
        @admin = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @admin.is_admin
            flash[:alert] = "You don't have permission"
            return redirect_to project_path(params[:project_id])
        end
        @group = Group.find_by(user_id: group_params[:user_id], project_id: group_params[:project_id])
        if not @group.nil?
            flash[:error] = "User with this project already exists!"
            return redirect_to project_path(params[:project_id])
        end

        @group = Group.new(group_params)

        respond_to do |format|
            if @group.save
                flash[:alert] = "Succesfully created group!"
                return redirect_to project_path(params[:project_id])
            else
                flash[:error] = "Error when created group!"
                return redirect_to project_path(params[:project_id])
            end
        end
    end

    def update
        @group = Group.find(params[:id])
        @group.update(is_admin: group_params[:is_admin] == "1")
        redirect_to project_path(params[:project_id])
    end

    def destroy
        Group.delete_by(user_id: params[:id], project_id: params[:project_id])
        redirect_to request.referer
    end

    private
    def group_params
        params.require(:groups).permit(:user_id, :project_id, :is_admin)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :check_signed_in

    def check_signed_in
        redirect_to project_index_path if signed_in?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def create
        @message = Topic.find(params[:topic_id]).message.build(message_params)
        @message[:user_id] = current_user.id

        if @message.save
            flash[:notice] = "Successfully message added!"
            redirect_to request.referer
        else
            flash[:alert] = "Failed to save"
            redirect_to request.referer
        end
    end

    def edit
        @message = Message.find(params[:id])
    end

    def update
        @message = Message.find(params[:id])
        if @message.update(message_params)
          flash[:success] = "Message updated!"
          redirect_to project_topic_path
        else
          flash.now[:error] = "Message update failed"
          redirect_to request.referer
        end
    end

    def destroy
        @message = Message.destroy(params[:id])
        redirect_to request.referer
    end

    private
    def message_params
        params.require(:message).permit(:message)
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    before_action :authenticate_user!

    def index 
        @projects = current_user.projects
    end

    def show
        @project = current_user.projects.find(params[:id])
        @all_users = [*User.all].delete_if { |user| user.id == current_user.id }
        @users = [*@project.user.select("*", "is_admin")].delete_if { |user| user.user_id == current_user.id }
        @group = @project.groups.find_by(user_id: current_user.id)
    end
    
    def create
        @project = Project.new(project_params)
        @error = @project.save
        @group = Group.create(user_id: current_user.id, project_id: @project.id, is_admin: true)

        respond_to do |format|
            if @error
                format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
                format.json { render :show, status: :created, location: @project }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        @project.update(project_params)
        redirect_to project_url(@project)
    end

    def destroy
        @is_admin = Group.find_by(user_id: current_user.id, project_id: params[:id])
        if not @is_admin.is_admin
            @group = Group.destroy_by(user_id: current_user.id, project_id: params[:id])
            return redirect_to project_index_path
        end
        @group = Group.destroy_by(project_id: params[:id])
        @project = Project.destroy(params[:id])
        @project.destroy()
        redirect_to project_index_path
    end


    private
    def project_params
        params.require(:project).permit(:title, :description)
    end

end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
    def index
        @project = Project.find(params[:project_id])
        @topics = @project.topic
        @group = @project.groups.find_by(user_id: current_user.id)
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def create
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @topic = Project.find(params[:project_id]).topic.build(topic_params)
        if @topic.save
            flash[:alert] = "Successfully created Topic"
            redirect_to project_topic_index_path(params[:project_id])
        else
            flash[:error] = "Error #{@topic.error}"
            redirect_to project_topic_index_path(params[:project_id])
        end
    end

    def update 
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @message = Topic.find(params[:id])
        if @message.update(topic_params)
          flash[:success] = "Topic updated!"
          redirect_to project_topic_index_path(params[:project_id], params[:id])
        else
          flash.now[:error] = "Topic updated failed"
          redirect_to request.referer
        end
    end

    def destroy
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @message = Message.destroy_by(topic_id: params[:id])
        @topic = Topic.destroy(params[:id])
        redirect_to request.referer
    end

    private
    def topic_params
        params.require(:topic).permit(:title)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_project_helper.rb
module AdminProjectHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/thread_helper.rb
module ThreadHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/messages/edit.html.erb
<div class="d-flex justify-content-center mt-5">
    <div style="width: 400px;">
        <div class="text-center"><h2>Edit Message</h2></div>
        <div class="mt-4">
            <%= form_for(:message, url: project_topic_message_path(params[:project_id], params[:topic_id], params[:id]), method: :put) do |f| %>
                <div class="field">
                    <%= f.text_field :message, value: @message.message, class: "form-control", placeholder: "Message" %>
                </div>
                <div class="field mt-2 d-flex justify-content-end">
                    <%= f.submit "Edit", disable_with: 'Editing...', class: "btn btn-success" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/project/edit.html.erb
<div class="mt-5 d-flex justify-content-center"> 
  <div style="width: 400px;">
    <div class="text-center">
      <h3>Update a Project</h3>
    </div>
    
    <%= form_for :project, url: project_path(@project.id), method: "put" do |form| %>
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, value: @project.title, placeholder: "Title", class: "form-control" %>
      </div>
      <div class="field mt-2">
        <%= form.label :description %>
        <%= form.text_field :description, value: @project.description, placeholder: "Description", class: "form-control" %>
      </div>
      <div class="d-flex justify-content-end">
        <%= form.submit value: "Submit", class: "btn btn-success mt-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/project/index.html.erb
<div class="mt-5 border rounded p-4" style="display: grid;grid-template-columns: repeat(3, minmax(0, 1fr));">
    <% if @projects.empty? %>
        <div>
            <div><h2>No Projects</h2></div>
            <%= link_to "Append Project", new_project_path, class: "btn btn-success" %>
        </div>
    <% end %>
    <% @projects.each do |project| %>
        <div class="card m-2">
            <div class="card-body">
                <h5 class="card-title"><%= project.title %></h5>
                <p class="card-text"><%= project.description %></p>
                <%= link_to "Show Project", project_path(project.id), class: "card-link" %>
            </div>
        </div>
    <% end %>
</div>

app/views/project/new.html.erb
<div class="mt-5 d-flex justify-content-center"> 
  <div style="width: 400px;">
    <div class="text-center">
      <h3>Create a Project</h3>
    </div>
    
    <%= form_for :project, url: project_index_path, method: "post" do |form| %>
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
      </div>
      <div class="field mt-2">
        <%= form.label :description %>
        <%= form.text_field :description, placeholder: "Description", class: "form-control" %>
      </div>
      <div class="d-flex justify-content-end">
        <%= form.submit value: "Submit", class: "btn btn-success mt-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/project/show.html.erb
<div class="mt-5 border rounded">
    <div>
        <div class="text-center border-bottom">
            <h1><%= @project.title %></h1>
        </div>
        <div class="border-bottom">
            <div class="text-center"><span>Description:</span></div>
            <div class="p-2"><p class="mt-2"><%= @project.description %></p></div>
        </div>
        <div class="d-flex justify-content-end">
            <div class="d-flex align-items-center p-2">
                <%= link_to "Attachments", project_attachments_path(params[:id]), class: "link-dark" %>
                <%= link_to "Append Thread", project_topic_index_path(params[:id]), class: "link-dark mx-2" %>
                <%= link_to "Edit Project", edit_project_path(@project.id), class: "link-dark" %>
                <%= button_to "Destroy", project_path(params[:id]), method: :delete, class: "btn btn-danger py-1 mx-2" %>
            </div>
        </div>
    </div>
</div>
<% if @group.is_admin %>
    <div class="border rounded mt-5">
        <div class="text-center border-bottom">
            <h2>Append user to this project</h2>
        </div>
        <%= form_for(:groups, url: project_group_index_path(params[:id]), method: "post", class: "d-flex align-items-center p-2") do |f| %>
            <%= f.collection_select :user_id, @all_users, :id, :email, {:prompt => "Select User"}, {:class=>'form-select'} %>
            <%= f.hidden_field :project_id, value: params[:id] %>
            <div class="form-check mx-3">
                <%= f.check_box :is_admin, class: "form-check-input" %>
                <%= f.label :is_admin, "Admin" %>
            </div>
            <%= f.submit "Append", disable_with: 'Appending...', class: "btn btn-success" %>
        <% end %>
    </div>
    <%= render "project/group/list_users"%>
<% end %>

app/views/topic/_new.html.erb
<div class="border rounded">
    <div class="text-center border-bottom p-1"><h3 class="m-0">New Topic</h3></div>
    <%= form_for(:topic, url: project_topic_index_path(params[:project_id]), class: "d-flex p-2") do |f| %>
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
        <%= f.submit "Append", disable_with: 'Appending...', class: "btn btn-success mx-3" %>
    <% end %>
</div>

app/views/topic/_topic.html.erb
<% @topics.each do |topic| %>
    <div class="border rounded mt-5">
        <div class="border-bottom p-2 d-flex justify-content-between align-items-center px-3">
            <h2 class="m-0"><%= topic.title %></h2>
            <% if @group.is_admin %>
                <div class="d-flex align-items-center">
                    <%= link_to "Edit Topic", edit_project_topic_path(params[:project_id], topic.id), class: "link-dark mx-3" %>
                    <%= button_to "Delete", project_topic_path(params[:project_id], topic.id), method: :delete, class: "btn btn-danger" %>
                </div>
            <% end %>
        </div>
        <div class="p-3">
            <% topic.message.each do |message| %>
                <div class="d-flex justify-content-between">
                    <% if message.user_id == current_user.id %>
                        <div>
                            <p class="font-weight-bold text-dark m-0"><%= User.find(message.user_id).full_name %>:</p>
                            <p class=""><%= message.message %></p>
                        </div>
                    <% else %>
                        <div>
                            <p class="font-weight-bold text-secondary m-0"><%= User.find(message.user_id).full_name %>:</p>
                            <p class=""><%= message.message %></p>
                        </div>
                    <% end %>
                    <div class="mt-3 d-flex">
                        <%= link_to "Edit", edit_project_topic_message_path(params[:project_id], topic.id, message.id), class: "link-dark mx-3" %>
                        <%= button_to "Del", project_topic_message_path(params[:project_id], topic.id, message.id), method: :delete, class: "btn btn-danger px-2 py-0" %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="border">
            <%= form_for(:message, url: project_topic_messages_path(params[:project_id], topic.id), class: "d-flex p-2") do |f| %>
                <%= f.text_field :message, class: "form-control", placeholder: "Message" %>
                <%= f.submit "Send", disable_with: 'Sending...', class: "btn btn-success px-4 mx-2" %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/topic/edit.html.erb
<div class="d-flex justify-content-center mt-5">
    <div style="width: 400px;">
        <div class="text-center"><h2>Edit Topic</h2></div>
        <div class="mt-4">
            <%= form_for(:topic, url: project_topic_path(params[:project_id], params[:id]), method: :put) do |f| %>
                <div class="field">
                    <%= f.text_field :title, value: @topic.title, class: "form-control", placeholder: "Title" %>
                </div>
                <div class="field mt-2 d-flex justify-content-end">
                    <%= f.submit "Edit", disable_with: 'Editing...', class: "btn btn-success" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/topic/index.html.erb
<% if @group.is_admin %>
    <div class="border rounded mt-5">
        <%= render 'topic/new' %>
    </div>
<% end %>

<div>
    <%= render "topic/topic" %>
</div>