config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :project do 
    resources :group
    resources :attachments
    resources :topic do
      resources :messages
    end
  end
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :topic
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :groups
    has_many :user, through: :groups
    has_many :topic
    has_many_attached :files
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :project
    has_many :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :groups, dependent: :destroy
  has_many :projects, through: :groups

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
    def index
        @project = Project.find(params[:project_id])
    end

    def create
        @project = Project.find(params[:project_id])
        @project.files.attach(attachments_params[:files])
        @project.save()
        redirect_to request.referer
    end

    def destroy
        @files = ActiveStorage::Attachment.find(params[:id])
        @files.purge
        redirect_to request.referer
    end

    private
    def attachments_params
        params.require(:attachment).permit(files: [])
    end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
    
    def create
        @admin = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @admin.is_admin
            flash[:alert] = "You don't have permission"
            return redirect_to project_path(params[:project_id])
        end
        @group = Group.find_by(user_id: group_params[:user_id], project_id: group_params[:project_id])
        if not @group.nil?
            flash[:error] = "User with this project already exists!"
            return redirect_to project_path(params[:project_id])
        end

        @group = Group.new(group_params)

        respond_to do |format|
            if @group.save
                flash[:alert] = "Succesfully created group!"
                return redirect_to project_path(params[:project_id])
            else
                flash[:error] = "Error when created group!"
                return redirect_to project_path(params[:project_id])
            end
        end
    end

    def update
        @group = Group.find(params[:id])
        @group.update(is_admin: group_params[:is_admin] == "1")
        redirect_to project_path(params[:project_id])
    end

    def destroy
        Group.delete_by(user_id: params[:id], project_id: params[:project_id])
        redirect_to request.referer
    end

    private
    def group_params
        params.require(:groups).permit(:user_id, :project_id, :is_admin)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :check_signed_in

    def check_signed_in
        redirect_to project_index_path if signed_in?
    end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
    def index
        @project = Project.find(params[:project_id])
        @topics = @project.topic
        @group = @project.groups.find_by(user_id: current_user.id)
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def create
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @topic = Project.find(params[:project_id]).topic.build(topic_params)
        if @topic.save
            flash[:alert] = "Successfully created Topic"
            redirect_to project_topic_index_path(params[:project_id])
        else
            flash[:error] = "Error #{@topic.error}"
            redirect_to project_topic_index_path(params[:project_id])
        end
    end

    def update 
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @message = Topic.find(params[:id])
        if @message.update(topic_params)
          flash[:success] = "Topic updated!"
          redirect_to project_topic_index_path(params[:project_id], params[:id])
        else
          flash.now[:error] = "Topic updated failed"
          redirect_to request.referer
        end
    end

    def destroy
        @group = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @group.is_admin
            flash[:error] = "You don't have access to this operation!"
        end
        @message = Message.destroy_by(topic_id: params[:id])
        @topic = Topic.destroy(params[:id])
        redirect_to request.referer
    end

    private
    def topic_params
        params.require(:topic).permit(:title)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_project_helper.rb
module AdminProjectHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/thread_helper.rb
module ThreadHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/attachments/_form.html.erb
<div class="field" style="width: 550px;" >
    <%= form_for :attachment, url: project_attachments_path(params[:project_id]), method: :post, multipart: true do |f| %>
        <div class="d-flex">
            <%= f.file_field :files, multiple: true, class: "form-control", type: "file" %>
            <%= f.submit "Add", class: "btn btn-dark w-25", style: "margin-left: 10px;" %>
        </div>
    <% end %>
</div>

app/views/attachments/_list_files.html.erb
<% if @project.files.attached? %>
    <% @project.files.each do |file| %>
        <% if file.image? %>
            <div class="col" style="position: relative; width: 200px; height: 180px;">
                <%= image_tag(file, class: "img-thumbnail", style: "width: 100%; height: 100%; object-fit: contain;") %>
                <div style="position: absolute; bottom: 5%; right: 10%">
                    <%= button_to "Delete", project_attachment_path(params[:project_id], file.id), method: :delete, class: "btn btn-danger" %>
                </div>
            </div>
        <% else %>
            <div class="border rounded col" style="width: 200px; height: 180px; position: relative;">
                <div class="text-center mt-2">
                    <%= link_to file.filename, url_for(file) , class: "link-dark" %>
                </div>
                <div style="position: absolute; bottom: 5%; right: 5%">
                    <%= button_to "Delete", project_attachment_path(params[:project_id], file.id), method: :delete, class: "btn btn-danger" %>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/attachments/index.html.erb
<div class="mt-5 d-flex flex-column align-items-center" >
    <div class="text-center">
        <h3>Attachments</h3>
    </div>
    <div class="mt-4">
        <%= render "form"%>
    </div>

    <div class="row row-cols-3 mt-4">
        <%= render "list_files", project: @project %>
    </div>
</div>