config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :project do 
    resources :group
    resources :attachments
    resources :topic do
      resources :messages
    end
  end
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :groups
    has_many :user, through: :groups
    has_many :topic
    has_many_attached :files
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
    
    def create
        @admin = Group.find_by(user_id: current_user.id, project_id: params[:project_id])
        if not @admin.is_admin
            flash[:alert] = "You don't have permission"
            return redirect_to project_path(params[:project_id])
        end
        @group = Group.find_by(user_id: group_params[:user_id], project_id: group_params[:project_id])
        if not @group.nil?
            flash[:error] = "User with this project already exists!"
            return redirect_to project_path(params[:project_id])
        end

        @group = Group.new(group_params)

        respond_to do |format|
            if @group.save
                flash[:alert] = "Succesfully created group!"
                return redirect_to project_path(params[:project_id])
            else
                flash[:error] = "Error when created group!"
                return redirect_to project_path(params[:project_id])
            end
        end
    end

    def update
        @group = Group.find(params[:id])
        @group.update(is_admin: group_params[:is_admin] == "1")
        redirect_to project_path(params[:project_id])
    end

    def destroy
        Group.delete_by(user_id: params[:id], project_id: params[:project_id])
        redirect_to request.referer
    end

    private
    def group_params
        params.require(:groups).permit(:user_id, :project_id, :is_admin)
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
    before_action :authenticate_user!

    def index 
        @projects = current_user.projects
    end

    def show
        @project = current_user.projects.find(params[:id])
        @all_users = [*User.all].delete_if { |user| user.id == current_user.id }
        @users = [*@project.user.select("*", "is_admin")].delete_if { |user| user.user_id == current_user.id }
        @group = @project.groups.find_by(user_id: current_user.id)
    end
    
    def create
        @project = Project.new(project_params)
        @error = @project.save
        @group = Group.create(user_id: current_user.id, project_id: @project.id, is_admin: true)

        respond_to do |format|
            if @error
                format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
                format.json { render :show, status: :created, location: @project }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @project.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])
        @project.update(project_params)
        redirect_to project_url(@project)
    end

    def destroy
        @is_admin = Group.find_by(user_id: current_user.id, project_id: params[:id])
        if not @is_admin.is_admin
            @group = Group.destroy_by(user_id: current_user.id, project_id: params[:id])
            return redirect_to project_index_path
        end
        @group = Group.destroy_by(project_id: params[:id])
        @project = Project.destroy(params[:id])
        @project.destroy()
        redirect_to project_index_path
    end


    private
    def project_params
        params.require(:project).permit(:title, :description)
    end

end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/project/group/_list_users.html.erb
<div class="mt-5 border rounded">
    <div>
        <div class="text-center border-bottom">
            <h2>Members:</h2>
        </div>
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Email</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <th scope="row"><%= user.user_id %></th>
                        <td><%= user.email %></td>
                        <td><%= user.full_name %></td>
                        <td>
                            <%= form_for(:groups, url: project_group_path(params[:id], user.id), method: :put) do |f| %>
                                <div class="form-check form-switch">
                                    <%= f.check_box :is_admin, checked: user.is_admin, class: "form-check-input", :onclick => "this.form.submit()" %>
                                    <%= f.label :is_admin, "Admin", class: "form-check-label" %>
                                </div>

                            <% end %>
                        </td>
                        <td>
                            <%= button_to "Destroy", project_group_path(params[:id], user.user_id), method: :delete, class: "btn btn-danger py-0 px-2" %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>